# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

# Define a job to be invoked later in a workflow.
jobs:
  ci:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: Go Test
          command: |
            go test -v -short --count=1 $(go list ./...)
      - run: echo "Testing Done"

  cd:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: view env
          command: |
            echo $REMOTE_HOST
      - run:
          name: Ping env
          command: |
            ping $REMOTE_HOST

# Orchestrate jobs using workflows
workflows:
  ci-and-cd-karsajobs:
    jobs:
      - ci
      - cd
